

ERROR_CODE_1 = "A PROBLEM OCCURRED WHILE CONNECTING WITH THE TRIPLE STORE."

ERROR_CODE_2 = "LINKSET [#] ALREADY EXISTS. \nTO PROCEED ANYWAY, PLEASE DELETE THE LINKSET."

ERROR_CODE_3 = "LINKSET [#] ALREADY EXISTS \nAS [@].\nTO PROCEED ANYWAY, PLEASE DELETE [@].\n"

ERROR_CODE_4 = "NO TRIPLE WAS INSERTED FOR THIS ACTION. THIS COULD BE DUE TO A NUMBER OF REASONS:\n" \
               "  - BAD PREDICATE ALIGNMENT\n  - NO MATCH FOUND (ASSUMING A CORRECT ALIGNMENT\n" \
               "  - INTERNAL PROBLEM)"

# DO NOT CHANE ERROR_CODE_5 CAUSE
ERROR_CODE_5 = "No connection could be made because the target machine actively refused it."


ERROR_CODE_6 = "LINKSET [#] ALREADY EXISTS. \nTO PROCEED ANYWAY, PLEASE DELETE THE LINKSET."

ERROR_CODE_7 = "lENS [#] ALREADY EXISTS \nAS [@].\nTO PROCEED ANYWAY, PLEASE DELETE [@]."

ERROR_CODE_8 = "THERE IS A PROBLEM WITH THIS GRAPH: #" \
               "\nEITHER BECAUSE THE GRAPH HAS NO METADATA WHERE THE NUMBER OF TRIPLES COULD BE FOUND" \
               "\nOR THE GRAPH SIMPLY DOES NOT EXIST."

ERROR_CODE_9 = "NO TRIPLES WHERE INSERTED FOR THIS ACTION.\nFOR THAT WE DO NOT INSERT METADATA FOR NON EXISTING LENS."

ERROR_CODE_10 = "ONE OF THE GRAPHS DOES NOT EXIST."